import type { Metadata } from "next";
import { Geist, Pixelify_Sans } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const pixelChrome = Pixelify_Sans({
  variable: "--font-pixel-chrome",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Lattice — Desktop",
  description:
    "A retro desktop portfolio: open the folders to explore projects.",
  // Favicon set generated by RealFaviconGenerator, served from `public/`.
  // The `app/favicon.ico` file convention was deleted in favour of these:
  // it also owns the `/favicon.ico` route, so keeping both would shadow
  // `public/favicon.ico` and emit a duplicate `<link rel="icon">`.
  icons: {
    icon: [
      { url: "/favicon-96x96.png", type: "image/png", sizes: "96x96" },
      { url: "/favicon.svg", type: "image/svg+xml" },
    ],
    shortcut: "/favicon.ico",
    apple: { url: "/apple-touch-icon.png", sizes: "180x180" },
  },
  other: { "apple-mobile-web-app-title": "Lattice" },
  manifest: "/site.webmanifest",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${pixelChrome.variable} h-full antialiased`}
    >
      <body className="h-full">{children}</body>
    </html>
  );
}
