import type { Metadata, Viewport } from "next";
import { Geist, Pixelify_Sans } from "next/font/google";
import { iconLayoutBootScript } from "@/components/desktop/iconLayout";
import { site, SITE_URL } from "@/content/site";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const pixelChrome = Pixelify_Sans({
  variable: "--font-pixel-chrome",
  subsets: ["latin"],
});

const title = `${site.name} — ${site.tagline}`;

export const metadata: Metadata = {
  // Resolves every relative URL below (canonical, the generated OG image) to
  // an absolute one. Without it Next emits relative `og:image` paths, which
  // unfurlers and crawlers drop without reporting an error.
  metadataBase: new URL(SITE_URL),
  title: {
    default: title,
    // Any future route exporting `title: "Foo"` renders as "Foo — Lattice".
    template: `%s — ${site.name}`,
  },
  description: site.description,
  applicationName: site.name,
  keywords: [...site.keywords],
  // The studio is the author of record, not any individual. The founder is
  // represented only as a linked Person node in the JSON-LD graph.
  authors: [{ name: site.name, url: SITE_URL }],
  creator: site.name,
  publisher: site.name,
  category: "technology",
  // Single-route site, so the canonical is always the origin. This is what
  // stops `?utm_source=…` and `?fbclid=…` variants splitting ranking signals.
  alternates: { canonical: "/" },
  openGraph: {
    type: "website",
    url: "/",
    siteName: site.name,
    title,
    description: site.description,
    locale: "en_US",
    // Images come from app/opengraph-image.tsx via the file convention.
  },
  twitter: {
    card: "summary_large_image",
    title,
    description: site.description,
    // No `creator` handle set — add one here if there is an X account to
    // attribute, otherwise the tag is better absent than wrong.
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      // Let Google use full-size image previews and unlimited snippet length
      // in results and AI Overviews; both default to conservative limits.
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  // Favicon set generated by RealFaviconGenerator, served from `public/`.
  // The `app/favicon.ico` file convention was deleted in favour of these:
  // it also owns the `/favicon.ico` route, so keeping both would shadow
  // `public/favicon.ico` and emit a duplicate `<link rel="icon">`.
  icons: {
    icon: [
      { url: "/favicon-96x96.png", type: "image/png", sizes: "96x96" },
      { url: "/favicon.svg", type: "image/svg+xml" },
    ],
    shortcut: "/favicon.ico",
    apple: { url: "/apple-touch-icon.png", sizes: "180x180" },
  },
  other: { "apple-mobile-web-app-title": site.name },
  // The manifest link is injected automatically by app/manifest.ts.
};

export const viewport: Viewport = {
  themeColor: site.themeColor,
  // The desktop is drawn in one fixed palette; declaring it stops browsers
  // from force-darkening the chrome.
  colorScheme: "light",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${pixelChrome.variable} h-full antialiased`}
    >
      <body className="h-full">
        {/* Must precede the desktop markup and stay render-blocking: it
            restores a saved icon arrangement before the browser's first paint.
            See iconLayoutBootScript for why an effect cannot do this. */}
        <script dangerouslySetInnerHTML={{ __html: iconLayoutBootScript() }} />
        {children}
      </body>
    </html>
  );
}
